# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Блог
email: https://github.com/RDinis228
description:  Ласкаво прошу всіх у мій блог. Даний записник створений для того, щоб допомогти аматорам розібратися з фреймворком Jekyll, та навчити їх створювати свої власні проекти.
baseurl: "/jekyll-wing-template" # the subpath of your site, e.g. /blog
url: "https://github.com/RDinis228" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

permalink: /:title.html

# Build settings
markdown: kramdown
gems: 
  - jekyll-paginate
  - jekyll-sitemap
paginate: 5