---
title: Блог
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: https://github.com/RDinis228
description: Ласкаво прошу всіх у мій блог. Даний записник створений для того, щоб
  допомогти аматорам розібратися з фреймворком Jekyll, та навчити їх створювати свої
  власні проекти.
baseurl: https://rdinis228.github.io/
url: https://github.com/RDinis228
twitter_username: jekyllrb
github_username: jekyll
permalink: "/:title"
markdown: kramdown
gems:
- jekyll-paginate
- jekyll-sitemap
paginate: 5
